security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        App\Entity\Voter: 'auto'
        App\Entity\PartyAgent: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_voter_provider:
            entity:
                class: App\Entity\Voter
                property: username
        app_agent_provider:
            entity:
                class: App\Entity\PartyAgent
                property: email

    firewalls:
        dev:
            # Ensure dev tools and static assets are always allowed
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        agent:
            pattern: ^/agent
            lazy: true
            provider: app_agent_provider
            form_login:
                login_path: app_agent_login
                check_path: app_agent_login
                username_parameter: _username
                password_parameter: _password
                enable_csrf: true
            logout:
                path: app_agent_logout
                target: app_agent_login
        main:
            lazy: true
            provider: app_voter_provider
            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: _username
                password_parameter: _password
                enable_csrf: true
            logout:
                path: app_logout
                target: app_home

    # Note: Only the *first* matching rule is applied
    access_control:
        - { path: ^/agent/login, roles: PUBLIC_ACCESS }
        - { path: ^/agent, roles: ROLE_AGENT }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_VOTER }

when@test:
    security:
        password_hashers:
            # Password hashers are resource-intensive by design to ensure security.
            # In tests, it's safe to reduce their cost to improve performance.
            App\Entity\Voter:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon