framework:
    workflows:
        blog_publishing:
            type: state_machine
            marking_store:
                type: method
                property: status
            supports: [App\Entity\BlogPost]
            initial_marking: draft
            places: [draft, in_review, published, rejected]
            transitions:
                submit:
                    from: draft
                    to: in_review
                publish:
                    from: in_review
                    to: published
                reject:
                    from: in_review
                    to: rejected
